reddit:
  base-url: https://www.reddit.com/r/
  domain: https://www.reddit.com

aws:
  access-key: <secret>
  key-id: <secret>


assets:
  files: src/main/resources/assets/
  screenshots-folder: src/main/resources/assets/screenshots/
  movie: src/main/resources/assets/movie.mp4


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:


gmail:
  email: <secret>
  password: <secret>